spring:
  datasource:
    username: root
    password: aGuIqEjvGGQkUvlTffePVOmlusSFiGhP
    url: mysql://root:aGuIqEjvGGQkUvlTffePVOmlusSFiGhP@mysql.railway.internal:3306/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  data:
    jdbc:
      dialect: mysql
