spring:
  datasource:
    username: root
    password: my-secret-pw
    url: jdbc:mysql://localhost:3306/railway?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
