spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: my-secret-pw
#    url: jdbc:mysql://localhost:3306/railway?useSSL=false
    password: aGuIqEjvGGQkUvlTffePVOmlusSFiGhP
    url: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  data:
    jdbc:
      dialect: mysql
